@Api_HostAddress = https://localhost:44362
###  EJEMPLO

GET {{Api_HostAddress}}/api/ejemplo

###

POST {{Api_HostAddress}}/api/ejemplo
Content-Type: application/json

{
  "nombre": "string",
  "edad": 0,
  "email": "string"
}

###

GET {{Api_HostAddress}}/api/ejemplo/0

###

DELETE {{Api_HostAddress}}/api/ejemplo/0

###

PUT {{Api_HostAddress}}/api/ejemplo/0
Content-Type: application/json

{
  "nombre": "string",
  "edad": 0,
  "email": "string"
}

###
